import { useState } from 'react';
import { BarChart3, ChevronDown, ChevronRight, ClipboardList, LoaderCircle, Plus, X } from 'lucide-react';
import { EmptyState } from '../components/Common';
import { getItemExercise, getWorkoutItems, getWorkoutName } from '../utils/exercise';

function EvolutionPanel({ history, currentWeight }) {
  const hasHistory = history.length > 1;
  const points = hasHistory ? history.slice(-4) : [Math.max(0, currentWeight - 10), Math.max(0, currentWeight - 5), currentWeight];
  const max = Math.max(...points, 1);
  return <div className="mt-4 rounded-lg border border-orange-400/10 bg-orange-500/5 p-4"><div className="mb-4 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-orange-300">{hasHistory ? 'Histórico de carga' : 'Evolução simulada de carga'}</p><span className="text-xs text-zinc-400">Últimas {points.length} sessões</span></div><div className="flex h-24 items-end gap-3">{points.map((point, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><span className="text-xs font-bold text-white">{point} kg</span><div className="w-full max-w-20 rounded-t-md bg-gradient-to-t from-orange-600 to-orange-400 shadow-lg shadow-orange-500/25 transition-all" style={{ height: `${Math.max(12, (point / max) * 100)}%` }} /><span className="text-[10px] text-zinc-500">Sessão {index + 1}</span></div>)}</div></div>;
}

function WorkoutDetails({ workout, workouts, onClose }) {
  const [evolutionItem, setEvolutionItem] = useState(null);
  const items = getWorkoutItems(workout);
  return <div className="fixed inset-0 z-40 overflow-y-auto bg-black/75 p-4 backdrop-blur-sm sm:p-8"><section className="mx-auto my-6 max-w-3xl rounded-2xl border border-white/10 bg-gradient-to-br from-zinc-900 to-zinc-950 p-6 shadow-2xl shadow-orange-500/10"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-400">Detalhes do treino</p><h2 className="mt-1 text-3xl font-black text-white">{getWorkoutName(workout)}</h2></div><button onClick={onClose} className="rounded-lg p-2 text-zinc-400 transition hover:bg-white/10 hover:text-white" aria-label="Fechar detalhes"><X /></button></div><div className="mt-7 space-y-3">{items.map((item, index) => { const exercise = getItemExercise(item); const history = workouts.flatMap(getWorkoutItems).filter((savedItem) => { const savedExercise = getItemExercise(savedItem); return savedExercise.id && exercise.id ? String(savedExercise.id) === String(exercise.id) : savedExercise.nome === exercise.nome; }).map((savedItem) => Number(savedItem.peso) || 0); return <div key={item.id ?? `${exercise.id}-${index}`} className="rounded-xl border border-white/10 bg-zinc-950/80 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-white">{exercise.nome}</h3><p className="mt-1 text-sm text-zinc-400">{item.series} séries · {item.repeticoes} repetições · <span className="font-semibold text-orange-300">{item.peso} kg</span></p></div><button onClick={() => setEvolutionItem(evolutionItem === index ? null : index)} className="inline-flex items-center gap-2 rounded-lg border border-orange-400/20 bg-orange-500/10 px-3 py-2 text-xs font-bold text-orange-300 transition hover:bg-orange-500 hover:text-white"><BarChart3 size={15} /> Ver evolução de carga <ChevronDown size={14} className={`transition ${evolutionItem === index ? 'rotate-180' : ''}`} /></button></div>{evolutionItem === index && <EvolutionPanel history={history} currentWeight={Number(item.peso) || 0} />}</div>; })}</div></section></div>;
}

function WorkoutCard({ workout, onOpen }) {
  const itemCount = getWorkoutItems(workout).length;
  return <article className="rounded-2xl border border-white/10 bg-zinc-900/75 p-6 shadow-xl shadow-orange-500/10 transition duration-300 hover:-translate-y-1 hover:border-orange-400/30"><div className="mb-7 flex items-center justify-between"><span className="rounded-xl bg-orange-500/15 p-3 text-orange-300"><ClipboardList size={22} /></span><span className="text-xs font-bold uppercase tracking-wider text-zinc-500">{itemCount} exercício{itemCount !== 1 ? 's' : ''}</span></div><h2 className="text-xl font-bold text-white">{getWorkoutName(workout)}</h2><p className="mt-2 text-sm text-zinc-400">Treino personalizado pronto para a próxima sessão.</p><button onClick={onOpen} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white/10 px-4 py-3 text-sm font-bold text-white transition hover:bg-orange-500">Acessar treino <ChevronRight size={17} /></button></article>;
}

export default function MyWorkoutsScreen({ workouts, isLoading, onCreate }) {
  const [selectedWorkout, setSelectedWorkout] = useState(null);
  return <div className="mx-auto max-w-7xl px-5 pb-12 sm:px-8"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-400">Biblioteca de performance</p><h1 className="mt-1 text-3xl font-black text-white">Meus treinos</h1><p className="mt-2 text-zinc-400">Acesse seus treinos e acompanhe a evolução de cada carga.</p></div><button onClick={onCreate} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-orange-500/20 transition hover:bg-orange-400"><Plus size={18} /> Novo treino</button></header>{isLoading ? <div className="flex min-h-64 items-center justify-center text-zinc-400"><LoaderCircle className="mr-2 animate-spin" /> Carregando treinos...</div> : workouts.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{workouts.map((workout, index) => <WorkoutCard key={workout.id ?? `${getWorkoutName(workout)}-${index}`} workout={workout} onOpen={() => setSelectedWorkout(workout)} />)}</div> : <EmptyState text="Você ainda não salvou nenhum treino." actionLabel="Criar primeiro treino" onAction={onCreate} />}{selectedWorkout && <WorkoutDetails workout={selectedWorkout} workouts={workouts} onClose={() => setSelectedWorkout(null)} />}</div>;
}
