import { CheckCircle2, ClipboardList, LoaderCircle, Pencil, Trash2, X } from 'lucide-react';
import { ExerciseImage } from './Exercise';
import { NumberField } from './Common';

export function WorkoutCart({ workout, setWorkout, items, isSaving, onEdit, onRemove, onSave }) {
  return <aside className="h-fit rounded-2xl border border-white/10 bg-zinc-900/80 p-5 shadow-2xl shadow-orange-500/10 backdrop-blur lg:sticky lg:top-6"><div className="mb-5 flex items-center gap-2"><ClipboardList className="text-orange-400" size={21} /><h2 className="font-bold text-white">Treino em construção</h2></div><label className="mb-4 block text-xs font-semibold uppercase tracking-wider text-zinc-500">Nome do treino<input value={workout.nomeTreino} onChange={(event) => setWorkout((current) => ({ ...current, nomeTreino: event.target.value }))} className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm text-white outline-none transition focus:border-orange-500" placeholder="Ex.: Treino A" /></label><div className="my-5 border-t border-white/10" /><div className="max-h-64 space-y-3 overflow-y-auto pr-1">{items.length ? items.map((item) => <div key={item.id} className="rounded-xl border border-white/5 bg-zinc-950 p-3 transition hover:border-orange-400/20"><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold text-zinc-100">{item.exercicio.nome}</p><div className="flex gap-1"><button onClick={() => onEdit(item)} className="rounded p-1 text-zinc-500 transition hover:bg-orange-500/15 hover:text-orange-300" aria-label={`Editar ${item.exercicio.nome}`}><Pencil size={16} /></button><button onClick={() => onRemove(item.id)} className="rounded p-1 text-zinc-500 transition hover:bg-rose-500/15 hover:text-rose-400" aria-label={`Remover ${item.exercicio.nome}`}><Trash2 size={16} /></button></div></div><p className="mt-1 text-xs text-zinc-400">{item.series} séries · {item.repeticoes} reps · {item.peso} kg</p></div>) : <p className="py-5 text-center text-sm text-zinc-500">Seu treino ainda não possui exercícios.</p>}</div><button onClick={onSave} disabled={isSaving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-orange-500 px-4 py-3.5 text-sm font-bold text-white shadow-lg shadow-orange-500/20 transition hover:bg-orange-400 hover:shadow-orange-500/35 disabled:cursor-not-allowed disabled:opacity-60">{isSaving ? <LoaderCircle size={18} className="animate-spin" /> : <CheckCircle2 size={18} />}{isSaving ? 'Salvando...' : 'Salvar treino'}</button></aside>;
}

export function ItemModal({ exercise, isEditing, form, setForm, onClose, onSubmit }) {
  const updateField = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  return <div className="fixed inset-0 z-40 flex items-center justify-center bg-black/70 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><form onSubmit={onSubmit} className="w-full max-w-md overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-zinc-900 to-zinc-950 shadow-2xl shadow-orange-500/10"><ExerciseImage exercise={exercise} className="h-40 w-full object-cover" /><div className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-orange-400">{isEditing ? 'Editar exercício' : 'Adicionar ao treino'}</p><h2 className="mt-1 text-xl font-bold text-white">{exercise.nome}</h2></div><button type="button" onClick={onClose} className="rounded-lg p-1 text-zinc-400 transition hover:bg-zinc-800 hover:text-white"><X /></button></div><div className="mt-6 grid grid-cols-3 gap-3"><NumberField label="Séries" value={form.series} onChange={(value) => updateField('series', value)} min="1" step="1" /><NumberField label="Repetições" value={form.repeticoes} onChange={(value) => updateField('repeticoes', value)} min="1" step="1" /><NumberField label="Peso (kg)" value={form.peso} onChange={(value) => updateField('peso', value)} min="0" step="0.5" /></div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg px-4 py-2.5 text-sm font-semibold text-zinc-400 transition hover:text-white">Cancelar</button><button type="submit" className="rounded-lg bg-orange-500 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-orange-400">{isEditing ? 'Salvar alterações' : 'Adicionar exercício'}</button></div></div></form></div>;
}
